### ISSUE TITLE
Ugly artifacts in 2d simplex

### ISSUE THREAD

**Issue by EntityB** [ashima/webgl-noise#11]
Im experimencing some ugly artifacts in 2d simplex. 
It seems that pattern repeat itself faster then in 289. 

I experimenced it with iPad (iPad 2 mini I think). 

Could anyone point where the problem could be?

**Comment by EntityB** [comment]
Recent events force me to ask, would be possible to reimplement this noise with `precision mediump float`?

**Comment by stegu** [comment]
The problem here is that for compatibility with older versions of GLSL and with WebGL, the permutations are done by integer math with floating point variables.

I see no way to make the permutation polynomial method work with a 16-bit floating point representation. The permutation set would then have to be very small to keep the numbers in the range where the integers N and N+1 map to different representations, and the periodic artifacts from using such a small set of gradients would most probably be too strong to be acceptable.

If texture bandwidth is not a problem, I would recommend using the texture-based lookup table for the permutations, as demonstrated by the older version of noise which I link to on the wiki page in the section "Other noise implementations". The texture-heavy version is generally not as fast on mobile platforms, but on desktop GPUs it can actually be about twice as fast as the pure computational version.
