### ISSUE TITLE
Gradient to 3D Simplex Noise

### ISSUE THREAD

**Issue by JcBernack** [ashima/webgl-noise#12]
I tried to add the calculation of the noise gradient to the 3D Simplex Noise, but I have no idea how to check if my results are correct. Can somebody comment on this with a better understanding of the Simplex Noise algorithm?

```
float snoise(vec3 v, out vec3 grad)
{
    ......

    // Mix final noise value
    vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);
    vec4 m2 = m * m;
    vec4 m4 = m2 * m2;

    vec4 pdotx = vec4(dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3));

    vec4 temp = m2 * m * pdotx;
    grad = -8.0 * (temp.x * x0 + temp.y * x1 + temp.z * x2 + temp.w * x3);
    grad += m4.x * p0 + m4.y * p1 + m4.z * p2 + m4.w * p3;
    grad *= 42.0;

    return 42.0 * dot(m4, pdotx);
}
```

The implementation is based on code I found which either was not in GLSL or not in 3D, like this one: [srdnoise2.glsl](https://github.com/OpenGLInsights/OpenGLInsightsCode/blob/master/Chapter%2007%20Procedural%20Textures%20in%20GLSL/library/srdnoise2.glsl)

**Comment by stegu** [comment]
Yesterday, I posted versions of 2-D simplex noise in GLSL that are tileable, have analytical derivative and an option for rotating the gradients to create "flow noise". It's in "psrdnoise2D.glsl". Separate functions for different purposes, because of how GLSL works. (My C/C++ version of this is one function with conditionals that takes slightly different paths dependng on what you ask it to compute.)

I still didn't make a 3D version with analytic derivative, so I'm keeping this issue open for visibility. The solution above from JcBernack is correct, and extends to 4-D with only minor changes. The gradient of simplex noise in higher dimensions is just a sum of more terms, the terms themselves are basically the same. The polynomials are of the same degree, there are only 5 4-D expressions instead of 4 3-D ones.

**Comment by stegu** [comment]
Finally saw your pull request, and merged it. I thought I was not supposed to be the maintainer here, but it seems I am the only one still in attendance. Closing issue. Thank you, @JcBernack!
