### ISSUE TITLE
webgl

### ISSUE THREAD

**Issue by lzjjjjjjj** [ashima/webgl-noise#22]
webgl可以使用什么插件一起使用可以进行动画效果

**Comment by stegu** [comment]
I do not understand your language, and Google Translate tells me that your comment means "What plug-ins can be used together for animation effects". That is nonsense, so I must assume the translation is wrong and try to answer the question I think you might have.

These are GLSL functions, and you can use them separately or together in any GLSL shader, including GLSL for WebGL. Because there is no smart linker or preprocessor in the GLSL compilation environment, you might need to delete duplicate copies of the helper functions "mod289" and "permute" in cases where their type signatures are an exact match. Note that there are several overloaded versions of these functions for float and vec2/3/4 types, so not all of them will clash when you cut and paste two or more of these functions into the same shader.

**Comment by stegu** [comment]
Closing the issue for lack of any further communication from the submitter.
